/**
 * Copyright (c) 2011 - 2015, Lunifera GmbH (Gross Enzersdorf), Loetz KG (Heidelberg)
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *         Florian Pirchner - Initial implementation
 */


grammar xbase.extender.tests.Grammar with org.eclipse.xtext.xbase.annotations.XbaseWithAnnotations

import "http://www.eclipse.org/emf/2002/Ecore" as ecore
generate xbaseExtenderTests "http://www.lunigera.org/xtext-osgi-builder"

TestGrammar:
	'test' name=TestID '{'
	(testCases+=TestCase)*
	'}';

TestCase:
	'testcase' name=ID;

TestID returns ecore::EString:
	ID ('.' ID)*;
